export interface Skill {
  name: string;
  icon: string;
}

export type ClipColor = "brand" | "amber" | "violet" | "blue";

/** A single video "clip" on the career timeline. */
export interface TimelineClip {
  /** Track label, e.g. "V3". */
  track: string;
  /** Period chip shown under the track label, e.g. "25 · now". */
  period: string;
  title: string;
  subtitle: string;
  tags: string[];
  color: ClipColor;
  /** Position on the ruler, in the same units as `duration`. */
  start: number;
  /** Length on the ruler. */
  span: number;
}

/** The always-on "audio" track — rendered as a waveform of craft traits. */
export interface AudioClip {
  track: string;
  period: string;
  tags: string[];
  start: number;
  span: number;
  /** Optional audio file path under /public (for timeline playback). */
  source?: string;
}

export interface Timeline {
  /** Total ruler length; clip `start`/`span` are measured against this. */
  duration: number;
  clips: TimelineClip[];
  audio: AudioClip;
}

/** Filter rail for the work galleries — order here is the order shown on
 *  screen. Shared by /work and the "My Work" section on a member page. */
export const WORK_CATEGORIES = [
  "All",
  "Video Editing",
  "Motion Graphics",
  "Photography",
  "Videography",
  "Graphic Designing",
] as const;

export type WorkCategory = (typeof WORK_CATEGORIES)[number];

/** A portfolio piece shown in the "My Work" gallery. */
export interface WorkItem {
  id: string;
  title: string;
  /** 3–5 word line that sits under the title. */
  description: string;
  /** Filter chip this belongs to. */
  category: Exclude<WorkCategory, "All">;
  /** YouTube id — drives both the embed and the poster thumbnail. */
  youtubeId: string;
  /** Domains / services delivered on the project — rendered as pills. */
  tags: string[];
  /** Optional app-logo badge (a path under /public), e.g. a skill icon. */
  tool?: string;
}

/** A still shown in the masonry photo gallery (used instead of the video grid
 *  for the photographers / cinematographers). */
export interface PhotoItem {
  id: string;
  /** Image path under /public. */
  src: string;
  /** One-line caption laid over the top of the frame. */
  caption: string;
  /** Optional pill shown in the top-right corner of the frame. */
  category?: Exclude<WorkCategory, "All">;
}

export interface TeamMember {
  id: string;
  name: string;
  username: string;
  role: string;
  image: string;
  /** Short line under the name on the detail page. */
  tagline: string;
  bio: string;
  skills: Skill[];
  /** Optional personal timeline song path under /public. */
  song?: string;
  /** Photos orbiting the portrait on the detail page. Falls back to
   *  DEFAULT_GALLERY — swap in real project stills per person. */
  gallery?: string[];
  /** Career timeline shown on the detail page. When omitted, a role-derived
   *  default is generated by `getTimeline` from the member's own fields. */
  timeline?: Timeline;
  /** Portfolio pieces for the "My Work" gallery. Falls back to DEFAULT_WORK. */
  work?: WorkItem[];
  /** Stills for the masonry photo gallery. When present, "My Work" renders the
   *  photo grid instead of the video grid — used for the photographers. */
  photos?: PhotoItem[];
}

/** Placeholder stock photography for the orbiting arc. */
export const DEFAULT_GALLERY: string[] = [
  "/work/1.webp",
  "/work/2.webp",
  "/work/3.webp",
  "/work/4.webp",
  "/work/5.webp",
  "/work/6.webp",
  "/work/7.webp",
  "/work/8.webp",
  "/work/9.webp",
  "/work/10.webp",
  "/work/11.webp",
  "/work/12.webp",
  "/work/13.webp",
];

export const TEAM: TeamMember[] = [
  {
    id: "01",
    name: "Manvaditya Singh",
    username: "manavaditya",
    role: "VIDEO EDITOR",
    image: "/team/manavadityasingh.jpeg",
    tagline: "Motion, rhythm and timing",
    bio: "Creating scroll-stopping short-form edits with fast-paced storytelling and seamless transitions.",
    song: "/songs/MANAV.mp3",
    skills: [
      {
        name: "Adobe After Effects",
        icon: "/logos/adobe-after-effects-icon.png",
      },
      {
        name: "Adobe Premiere Pro",
        icon: "/logos/adobe-premiere-pro-icon.png",
      },
    ],
    work: [
            {
        id: "mv5",
        title: "CR7 Reunited",
        description: "High-energy sports montage.",
        category: "Video Editing",
        youtubeId: "SKaZAbTKxnY",
        tags: ["Sports", "Transitions"],
        tool: "/logos/adobe-after-effects-icon.png",
      },
      {
        id: "mv1",
        title: "IT'S NOT THE STATISTICS",
        description: "Character edit cut to the beat.",
        category: "Video Editing",
        youtubeId: "_8uDBBKoJ2o",
        tags: ["Short Form", "Film Edit"],
        tool: "/logos/adobe-premiere-pro-icon.png",
      },
      {
        id: "mv2",
        title: "Obsession in Cinema",
        description: "Montage on obsession in film.",
        category: "Video Editing",
        youtubeId: "t8F3fIOMsYA",
        tags: ["Montage", "Sound Design"],
        tool: "/logos/adobe-premiere-pro-icon.png",
      },
      {
        id: "mv3",
        title: "Another version of me",
        description: "Football edit with punchy pacing.",
        category: "Video Editing",
        youtubeId: "r5aJ9tG-lFA",
        tags: ["Sports", "Short Form"],
        tool: "/logos/adobe-after-effects-icon.png",
      },
      {
        id: "mv4",
        title: "Kohli — Let Down",
        description: "Cricket edit built around one track.",
        category: "Video Editing",    
        youtubeId: "upp20xwYB9Y",
        tags: ["Sports", "Colour Grade"],
        tool: "/logos/adobe-premiere-pro-icon.png",
      },

    ],
  },
  {
    id: "02",
    name: "Gaurav Agarwal",
    username: "gaurav",
    role: "VIDEO EDITOR/ MOTION DESIGNER",
    image: "/team/gauravagrawal.jpeg",
    tagline: "Light, frame and colour",
    bio: "Using professional editing and color grading software to craft polished, cinematic visuals",
    song: "/songs/GAURAV.mp3",
    skills: [
      { name: "DaVinci Resolve", icon: "/logos/DaVinci_Resolve_Studio.png" },
      { name: "Adobe Photoshop", icon: "/logos/adobe-photoshop-icon.png" },
      {
        name: "Adobe Premiere Pro",
        icon: "/logos/adobe-premiere-pro-icon.png",
      },
      {
        name: "Adobe After Effects",
        icon: "/logos/adobe-after-effects-icon.png",
      },
    ],
    work: [
      {
        id: "ga1",
        title: "Cinema As Art",
        description: "Visual essay on cinema as art.",
        category: "Video Editing",
        youtubeId: "NZEk-__pAt0",
        tags: ["Montage", "Colour Grade"],
        tool: "/logos/DaVinci_Resolve_Studio.png",
      },
      {
        id: "ga2",
        title: "Mosaic Motion Introductory Video",
        description: "Introductory film for Mosaic Motion.",
        category: "Videography",
        youtubeId: "b3874OrtkdI",
        tags: ["Brand Film", "Direction"],
        tool: "/logos/adobe-premiere-pro-icon.png",
      },
      {
        id: "ga3",
        title: "Poster Reveal After Movie (Intro Part)",
        description: "After-movie intro with poster reveal.",
        category: "Motion Graphics",
        youtubeId: "XeGg443DWOs",
        tags: ["Titles", "Animation"],
        tool: "/logos/adobe-after-effects-icon.png",
      },
      {
        id: "ga4",
        title: "Fotografreaks Recruitment Reel",
        description: "Recruitment reel for Fotografreaks.",
        category: "Videography",
        youtubeId: "_9rRNMOUHKE",
        tags: ["Campus", "Promo"],
        tool: "/logos/adobe-premiere-pro-icon.png",
      },
      {
        id: "ga5",
        title: "La La Land",
        description: "Film edit graded for warmth.",
        category: "Video Editing",
        youtubeId: "Co2l5pRdtYU",
        tags: ["Film Edit", "Colour Grade"],
        tool: "/logos/DaVinci_Resolve_Studio.png",
      },
      {
        id: "ga6",
        title: "Barfi X Can't Help Falling In Love",
        description: "Film tribute cut to score.",
        category: "Video Editing",
        youtubeId: "Qf_9P3uq2LM",
        tags: ["Film Edit", "Sound Design"],
        tool: "/logos/DaVinci_Resolve_Studio.png",
      },
    ],
  },
  {
    id: "03",
    name: "Ritul Tripathi",
    username: "ritul",
    role: "GRAPHIC DESIGNER, ILLUSTRATOR, VISUAL ARTIST",
    image: "/team/ritultripathi.jpeg",
    tagline: "Ideas built into pixels",
    bio: "I turn ideas into bold visuals that stand out. From branding and illustrations to animation and graphic design",
    song: "/songs/RITUL.mp3",
    skills: [
      {
        name: "Canva",
        icon: "/logos/canva-icon.png",
      },
      { name: "Adobe", icon: "/logos/adobe-icon.png" },
      { name: "Pro Create", icon: "/logos/Procreate_logo.png" },
    ],
    photos: [
      { id: "rp1", src: "/work/ritul/thaely-03.webp", caption: "Thaely — campaign key visual", category: "Graphic Designing" },
      { id: "rp2", src: "/work/ritul/thaely-08.webp", caption: "Thaely — product layout", category: "Graphic Designing" },
      { id: "rp3", src: "/work/ritul/thaely-10.webp", caption: "Thaely — closing frame", category: "Graphic Designing" },
      { id: "rp4", src: "/work/ritul/magazine-05.webp", caption: "Magazine spread, editorial grid", category: "Graphic Designing" },
      { id: "rp5", src: "/work/ritul/publication-01.webp", caption: "Publication cover, bold type", category: "Graphic Designing" },
      { id: "rp6", src: "/work/ritul/poster-frame-mockup.webp", caption: "Poster series in frame", category: "Graphic Designing" },
      { id: "rp7", src: "/work/ritul/wine-box-mockup.webp", caption: "Packaging mock, wine box", category: "Graphic Designing" },
      { id: "rp8", src: "/work/ritul/money-in-the-bank.webp", caption: "Money in the Bank — poster", category: "Graphic Designing" },
      { id: "rp9", src: "/work/ritul/ritul-01.webp", caption: "Brand identity, first pass", category: "Graphic Designing" },
      { id: "rp10", src: "/work/ritul/ritul-02.webp", caption: "Illustration study in colour", category: "Graphic Designing" },
      { id: "rp15", src: "/work/ritul/4.webp", caption: "Cinematic product frame", category: "Graphic Designing" },
      { id: "rp11", src: "/work/ritul/ritul-03.webp", caption: "Visual system, one grid", category: "Graphic Designing" },
      { id: "rp12", src: "/work/ritul/ritul-05.webp", caption: "Type experiment, late night", category: "Graphic Designing" },
      { id: "rp13", src: "/work/ritul/ritul-06.webp", caption: "Layout exploration", category: "Graphic Designing" },
      { id: "rp14", src: "/work/ritul/ritul-07.webp", caption: "Poster study, bold colour", category: "Graphic Designing" },
    ],
  },
  {
    id: "04",
    name: "Arihan Jain",
    username: "arihant",
    role: "VIDEO EDITOR",
    image: "/team/arihanjain.jpg",
    tagline: "Ideas built into pixels",
    bio: "I specialize in flow-style edits, dynamic pacing, and immersive sound design. From viral editing styles to seamless transitions",
    song: "/songs/ARIHAN.mp3",
    skills: [
      {
        name: "Adobe After Effects",
        icon: "/logos/adobe-after-effects-icon.png",
      },
      {
        name: "Adobe Premiere Pro",
        icon: "/logos/adobe-premiere-pro-icon.png",
      },
    ],
    work: [
      {
        id: "ar1",
        title: "Bismil — JECRC",
        description: "Fest performance cut for impact.",
        category: "Video Editing",
        youtubeId: "-pL3yZ8FCrI",
        tags: ["Event", "Short Form"],
        tool: "/logos/adobe-premiere-pro-icon.png",
      },
      {
        id: "ar2",
        title: "College Fest BMX Montage",
        description: "BMX montage from a college fest.",
        category: "Video Editing",
        youtubeId: "VWwzGoecfO8",
        tags: ["Montage", "Event"],
        tool: "/logos/adobe-premiere-pro-icon.png",
      },
      {
        id: "ar3",
        title: "Light It Up — VBR '25",
        description: "Recap edit with dynamic pacing.",
        category: "Video Editing",
        youtubeId: "RwVj1BoSsRY",
        tags: ["Event", "Transitions"],
        tool: "/logos/adobe-after-effects-icon.png",
      },
      {
        id: "ar4",
        title: "LV Sandals Flow Style",
        description: "Product edit in flow style.",
        category: "Video Editing",
        youtubeId: "TeEmZGgRtII",
        tags: ["Product", "Flow Style"],
        tool: "/logos/adobe-after-effects-icon.png",
      },
      {
        id: "ar5",
        title: "Radiance Flow Style",
        description: "Flow-style edit with tight sound design.",
        category: "Video Editing",
        youtubeId: "7MFUZZsYeKo",
        tags: ["Flow Style", "Sound Design"],
        tool: "/logos/adobe-after-effects-icon.png",
      },
    ],
  },
  {
    id: "05",
    name: "Herain Deegwal",
    username: "herain",
    role: "PHOTOGRAPHER/ CINEMATOGRAPHER",
    image: "/team/Herain.jpg",
    tagline: "Ideas built into pixels",
    bio: "Always chasing the perfect frame. From photography and cinematography to camera handling, I create clean, cinematic visuals with purpose where every frame tells a story.",
    song: "/songs/HERAIN.mp3",
    skills: [
      { name: "Adobe Illustrator", icon: "/logos/adobe-illustrator-icon.png" },
      { name: "Adobe Photoshop", icon: "/logos/adobe-photoshop-icon.png" },
    ],
    photos: [
      { id: "hp1", src: "/work/herain/AKP06977.webp", caption: "Golden hour, one frame", category: "Photography" },
      { id: "hp2", src: "/work/herain/AKP06993.webp", caption: "Portrait study in natural light", category: "Photography" },
      { id: "hp3", src: "/work/herain/AKP07012.webp", caption: "On-set stills, campaign day", category: "Photography" },
      { id: "hp4", src: "/work/herain/DSC02842.webp", caption: "Cinematic frame, shallow depth", category: "Photography" },
      { id: "hp5", src: "/work/herain/DSC02891.webp", caption: "Available light, quiet moment", category: "Photography" },
      { id: "hp6", src: "/work/herain/DSC02907.webp", caption: "Behind the lens, live shoot", category: "Photography" },
      { id: "hp14", src: "/work/herain/DSC07941.webp", caption: "Frame held, natural light", category: "Photography" },
      { id: "hp15", src: "/work/herain/DSC08726.webp", caption: "On location, mid-shoot", category: "Photography" },
      { id: "hp16", src: "/work/herain/DSC09596.webp", caption: "Wide frame, open sky", category: "Photography" },
      { id: "hp17", src: "/work/herain/DSC09970.webp", caption: "Close crop, soft key", category: "Photography" },
      { id: "hp7", src: "/work/herain/Gem-3.webp", caption: "Product still, controlled light", category: "Photography" },
      { id: "hp8", src: "/work/herain/Gem-6.webp", caption: "Detail shot, macro pass", category: "Photography" },
      { id: "hp9", src: "/work/herain/IMG_0072.webp", caption: "Street textures after rain", category: "Photography" },
      { id: "hp10", src: "/work/herain/IMG_0176.webp", caption: "Wide open, natural frame", category: "Photography" },
      { id: "hp11", src: "/work/herain/IMG_0185.webp", caption: "Location scout, first light", category: "Photography" },
      { id: "hp12", src: "/work/herain/IMG_0452.webp", caption: "Editorial set, soft key", category: "Photography" },
      { id: "hp13", src: "/work/herain/IMG_0858.webp", caption: "Last light on location", category: "Photography" },
    ],
  },
  {
    id: "06",
    name: "Bharat Kumar",
    username: "bharat",
    role: "Photography/Cinematography",
    image: "/team/bharat.JPG",
    tagline: "Ideas built into pixels",
    bio: "A photographer and videographer capturing fresh, authentic moments with a cinematic touch. From quirky visuals to modern vlogs, I bring creativity and energy to every frame.",
    song: "/songs/BHARAT.mp3",
    skills: [
      { name: "Adobe Photoshop", icon: "/logos/adobe-photoshop-icon.png" },
      { name: "Adobe Illustrator", icon: "/logos/adobe-illustrator-icon.png" },
      {
        name: "Adobe Premiere Pro",
        icon: "/logos/adobe-premiere-pro-icon.png",
      },
    ],
    photos: [
      { id: "bp1", src: "/work/bharat/AKP09827.webp", caption: "Candid frames, no direction", category: "Photography" },
      { id: "bp2", src: "/work/bharat/AKP09869.webp", caption: "Vlog day, city run", category: "Photography" },
      { id: "bp3", src: "/work/bharat/AKP09879.webp", caption: "Colour graded on set", category: "Photography" },
      { id: "bp4", src: "/work/bharat/DSC00966.webp", caption: "Quirky light, quiet moment", category: "Photography" },
      { id: "bp5", src: "/work/bharat/DSC01273.webp", caption: "Lifestyle shoot, morning call", category: "Photography" },
      { id: "bp6", src: "/work/bharat/DSC01276.webp", caption: "Second look, same set", category: "Photography" },
      { id: "bp7", src: "/work/bharat/DSC01383.webp", caption: "Portrait, available light", category: "Photography" },
      { id: "bp8", src: "/work/bharat/DSC02728.webp", caption: "Event floor, wide frame", category: "Photography" },
      { id: "bp9", src: "/work/bharat/DSC02867.webp", caption: "Cinematic still, low key", category: "Photography" },
      { id: "bp10", src: "/work/bharat/DSC02906.webp", caption: "Motion caught mid-frame", category: "Photography" },
      { id: "bp11", src: "/work/bharat/DSC02978.webp", caption: "Frame from the last edit", category: "Photography" },
    ],
  },
  {
    id: "07",
    name: "Kunal Tak",
    username: "kunal",
    role: "Video Editor/ Motion Designer",
    image: "/team/kunal.jpg",
    tagline: "Ideas built into pixels",
    bio: "Turning ideas into motion with sleek animations and dynamic video edits that are clean, engaging, and built to stand out",
    song: "/songs/KUNAL.mp3",
    skills: [
      {
        name: "Adobe After Effects",
        icon: "/logos/adobe-after-effects-icon.png",
      },
      {
        name: "Adobe Premiere Pro",
        icon: "/logos/adobe-premiere-pro-icon.png",
      },
    ],
    work: [
      {
        id: "ku1",
        title: "Blinkit UI",
        description: "UI animation for the Blinkit app.",
        category: "Motion Graphics",
        youtubeId: "_GMpqG1uSPw",
        tags: ["UI Animation", "Product"],
      },
      {
        id: "ku2",
        title: "Drive UI",
        description: "Interface motion study for Drive.",
        category: "Motion Graphics",
        youtubeId: "hm9WIFPqnkk",
        tags: ["UI Animation", "Concept"],
      },
      {
        id: "ku3",
        title: "Wi-Fi",
        description: "Micro-interaction animated end to end.",
        category: "Motion Graphics",
        youtubeId: "1KpcDnbu6kw",
        tags: ["UI Animation", "Micro-interaction"],
      },
    ],
  },
];

export function getMemberByUsername(username: string) {
  return TEAM.find((member) => member.username === username);
}

const STOP_WORDS = new Set([
  "into",
  "with",
  "and",
  "the",
  "of",
  "for",
  "a",
  "an",
  "to",
  "on",
  "in",
]);

function titleCase(word: string) {
  return word.charAt(0).toUpperCase() + word.slice(1);
}

function songTag(songPath?: string): string | null {
  if (!songPath) return null;
  const raw = songPath.split("/").pop()?.replace(/\.[^.]+$/, "");
  if (!raw) return null;
  return raw
    .toLowerCase()
    .split(/[_\s-]+/)
    .map(titleCase)
    .join(" ");
}

/** Turn a tagline into a few "craft" words for the audio waveform track.
 *  "Motion, rhythm and timing" -> ["Motion", "Rhythm", "Timing"]. */
function craftWords(tagline: string): string[] {
  let parts = tagline
    .split(/,|\band\b/i)
    .map((part) => part.trim())
    .filter(Boolean);

  if (parts.length < 2) {
    parts = tagline
      .split(/\s+/)
      .filter((word) => word.length > 2 && !STOP_WORDS.has(word.toLowerCase()));
  }

  return parts.slice(0, 3).map(titleCase);
}

/** Short, tool-name tags: "Adobe After Effects" -> "After Effects". */
function skillTags(member: TeamMember): string[] {
  return member.skills.map((skill) => skill.name.replace(/^Adobe\s+/, ""));
}

/** The member's own timeline, or an honest default assembled from their role,
 *  skills and tagline — no fabricated employers or dates. */
export function getTimeline(member: TeamMember): Timeline {
  if (member.timeline) return member.timeline;

  const tools = skillTags(member);

  const songName = songTag(member.song);

  return {
    duration: 24,
    clips: [
      {
        track: "V3",
        period: "Now",
        title: "Blitz Pixel Media",
        subtitle: `${member.role} · Present`,
        tags: [...tools.slice(0, 2), "Bangalore"],
        color: "brand",
        start: 0,
        span: 22,
      },
      {
        track: "V2",
        period: "Craft",
        title: "Studio & Client Work",
        subtitle: "Sharpening the reel",
        tags: tools.slice(0, 3),
        color: "amber",
        start: 0,
        span: 18,
      },
      {
        track: "V1",
        period: "Roots",
        title: "Learning the Craft",
        subtitle: "Where it started",
        tags: ["Curiosity", "Practice"],
        color: "violet",
        start: 0,
        span: 11,
      },
    ],
    audio: {
      track: "A1",
      period: "Always",
      tags: songName ? [songName, "Timeline Song"] : craftWords(member.tagline),
      // Runs the full length of the sequence (00:00 → duration).
      start: 0,
      span: 24,
      source: member.song,
    },
  };
}

/** Placeholder portfolio — swap `member.work` in with real project videos.
 *  Uses open-content YouTube ids so the embeds and posters resolve. */
export const DEFAULT_WORK: WorkItem[] = [
  {
    id: "w1",
    title: "Acne Scars",
    description: "Skincare reel cut for retention and clean pacing.",
    category: "Video Editing",
    youtubeId: "aqz-KE-bpKQ",
    tags: ["Med Spa", "Social Media"],
    tool: "/logos/adobe-premiere-pro-icon.png",
  },
  {
    id: "w2",
    title: "Take It At Night",
    description: "Night-routine promo built around a single hook.",
    category: "Video Editing",
    youtubeId: "eRsGyueVLvQ",
    tags: ["Promo", "Colour Grade"],
    tool: "/logos/adobe-premiere-pro-icon.png",
  },

  {
    id: "w5",
    title: "Studio Sessions",
    description: "Multi-cam podcast set, shot and lit in-house.",
    category: "Videography",
    youtubeId: "LXb3EKWsInQ",
    tags: ["Podcast", "Multi-Cam"],
    tool: "/logos/DaVinci_Resolve_Studio.png",
  },
  {
    id: "w6",
    title: "Launch Day",
    description: "Product launch film shot across one day.",
    category: "Videography",
    youtubeId: "ScMzIvxBSi4",
    tags: ["Brand Film", "Direction"],
    tool: "/logos/DaVinci_Resolve_Studio.png",
  },
  {
    id: "w7",
    title: "Lookbook 01",
    description: "Studio product stills retouched for campaign use.",
    category: "Photography",
    youtubeId: "eRsGyueVLvQ",
    tags: ["Product", "Retouching"],
    tool: "/logos/adobe-lightroom-icon.png",
  },

  {
    id: "w9",
    title: "AXN",
    description: "Minimal streetwear identity with bold attitude.",
    category: "Graphic Designing",
    youtubeId: "R6MlUcmOul8",
    tags: ["Branding", "Social Media"],
    tool: "/logos/adobe-illustrator-icon.png",
  },
  {
    id: "w10",
    title: "Rivermark",
    description: "Street campaign system built to grab attention.",
    category: "Graphic Designing",
    youtubeId: "TLkA0RELQ1g",
    tags: ["Campaign", "Print"],
    tool: "/logos/adobe-photoshop-icon.png",
  },
];

/** The member's own portfolio, or the shared placeholder set. */
export function getWork(member: TeamMember): WorkItem[] {
  return member.work?.length ? member.work : DEFAULT_WORK;
}
